services:
  nginx:
    image: legionlord-nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /private/var/services/legionlord/nginx/letsencrypt:/etc/letsencrypt
    networks:
      - legionlord

networks:
  legionlord:
    external: true
    name: legionlord_default